base:
  nameServer : "base_nameServer"
  groupname : "base_groupname"

sub1:
  nameServer : "sub1_nameServer"
  groupname : "sub1_groupname"

sub2:
  nameServer : "sub2_nameServer"
  groupname : "sub2_groupname"

#数据库加密后密码
database:
  passwd: ENC(OtToysVnra2PAE1bJtkv6A==)


#spring:
#  application:
#    name: h3-pos-transmission
#  profiles:
#    active: dev
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.10.130:3306/h3-ware?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
#    username: agent
#    password: agent123
#    type: com.alibaba.druid.pool.DruidDataSource


spring:
  application:
    name: spring-boot-test
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/h3-pos?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: wjb#
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 6000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      filters: stat
      async-init: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.spboot.mapper

server:
  port: 8090
